apiVersion: v1
kind: Secret
metadata:
  name: mongo-atlas-credentials
  labels:
    app.kubernetes.io/part-of: mongo-tweets-app
stringData:
  MONGO_ATLAS_URI: "mongodb+srv://IRGC:iraniraniran@iranmaldb.gurutam.mongodb.net/?retryWrites=true&w=majority
"
type: Opaque